version: 2
jobs:
  build:
    docker:
      - image: node:8@sha256:9ad3309f2ab60bb09774cc774ed305bfcda71dca65730ba49073b7269de1cac6

    working_directory: ~/repo

    steps:
      - checkout:
          post: git pull --ff-only origin "refs/pull/${CIRCLE_PULL_REQUEST//*pull\//}/merge"

      - restore_cache:
          keys:
            - node8-{{ checksum "package.json" }}
            - node8-

      - run: npm install --quiet

      - save_cache:
          key: node8-{{ checksum "package.json" }}
          paths:
            - ~/repo/node_modules

      - run: npm run lint
