version: 2
jobs:
  build:
    docker:
      - image: node:8@sha256:625d0b446f63b2d051c7b2a468f6cee63536dec716f09afcf9ae1c575d9b953a

    working_directory: ~/repo

    steps:
      - checkout:
          post: git pull --ff-only origin "refs/pull/${CIRCLE_PULL_REQUEST//*pull\//}/merge"

      - restore_cache:
          keys:
            - node8-{{ checksum "package.json" }}
            - node8-

      - run: npm install --quiet

      - save_cache:
          key: node8-{{ checksum "package.json" }}
          paths:
            - ~/repo/node_modules

      - run: npm run lint

      - run: npm run build

      - run: npm run release
