version: 2
jobs:
  build:
    docker:
      - image: node:8@sha256:ceb6e9e47ec034664e795d7b7e45f288e2b47a5a51cc6015dc7d672252900788

    working_directory: ~/repo

    steps:
      - checkout:
          post: git pull --ff-only origin "refs/pull/${CIRCLE_PULL_REQUEST//*pull\//}/merge"

      - restore_cache:
          keys:
            - node8-{{ checksum "package.json" }}
            - node8-

      - run: npm install --quiet

      - save_cache:
          key: node8-{{ checksum "package.json" }}
          paths:
            - ~/repo/node_modules

      - run: npm run lint
