version: 2
jobs:
  build:
    docker:
      - image: node:8@sha256:98755b9281c251f9e712069978975181a9d9b43efcbe0f2270ff6206ebc86dda

    working_directory: ~/repo

    steps:
      - checkout:
          post: git pull --ff-only origin "refs/pull/${CIRCLE_PULL_REQUEST//*pull\//}/merge"

      - restore_cache:
          keys:
            - node8-{{ checksum "package.json" }}
            - node8-

      - run: npm install --quiet

      - save_cache:
          key: node8-{{ checksum "package.json" }}
          paths:
            - ~/repo/node_modules

      - run: npm run lint

      - run: npm run build

      - run: npm run release
